vivo-community/scholars-discovery

.gitignore
README.md

Related to https://github.com/vivo-community/scholars-discovery/issues/3

Add initial README

---

src/main/resources/defaults/displayViews.yml
src/main/resources/defaults/displayViews/grants/affiliation/contributor.html
src/main/resources/defaults/displayViews/organizations/affiliation/organizationForTraining.html
src/main/resources/defaults/displayViews/organizations/affiliation/organizationForTraining/default.html
src/main/resources/defaults/displayViews/people/academicBackground/educationAndTraining/default.html
src/main/resources/defaults/displayViews/people/publications/editorOf/default.html
src/main/resources/defaults/displayViews/publications/identity/digitalObjectIdentifier.html

Resolves #22 
Resolves #23 
Resolves #24 
Resolves #25 
Resolves #30 
Resolves #31

[TAMU Sprint6] Template Updates

---

src/main/resources/defaults/discoveryViews.yml

[28 TAMU Sprint 6] add research keywords facet to people and publications discovery views

---

src/main/java/edu/tamu/scholars/middleware/discovery/model/Person.java
src/main/resources/defaults/displayViews.yml
src/main/resources/templates/sparql/person/etdChairOfPublicationDate.sparql

[21 TAMU Sprint 6] Index publication date of chaired theses and sort

---

src/main/resources/templates/sparql/document/publicationVenue.sparql

[TAMU Sprint 6 20] Update document publicationVenue sparql

---

src/main/java/edu/tamu/scholars/middleware/discovery/model/Person.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/repo/impl/AbstractSolrDocumentRepoImpl.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/repo/impl/ConceptRepoImpl.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/repo/impl/DocumentRepoImpl.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/repo/impl/PersonRepoImpl.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/repo/impl/ProcessRepoImpl.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/repo/impl/RelationshipRepoImpl.java

[TAMU Sprint6 16] Discovery Query Boosting

---

src/main/resources/defaults/displayViews/grants/publications/supportedPublicationsOrOtherWorks.html

[TAMU Sprint 6 24] Complete supportedPublicationsOrOtherWorks template

---

src/main/resources/defaults/displayViews/organizations/overview/awardOrHonorGiven.html

[TAMU Sprint 6 57] Complete org award or honor given template

---

src/main/resources/defaults/directoryViews/people/default.html

Resolves: https://github.com/vivo-community/scholars-angular/issues/30

Check for 'undefined' position array in people/default.html

---

pom.xml

[TAMU Sprint 7 74] Add handlebars compiler dependency

---

src/main/java/edu/tamu/scholars/middleware/defaults/DisplayViewDefaults.java
src/main/java/edu/tamu/scholars/middleware/view/model/DisplayView.java
src/main/resources/defaults/displayViews.yml
src/main/resources/defaults/displayViews/defaults/embed/default.html
src/test/java/edu/tamu/scholars/middleware/view/ViewTestUtility.java
src/test/java/edu/tamu/scholars/middleware/view/controller/DisplayViewControllerTest.java
src/test/java/edu/tamu/scholars/middleware/view/model/DisplayViewTest.java

Default embed template, map of embed templates on display view

---

src/main/resources/defaults/displayViews/people/publications/selectedPublications/default.html

Fixed dimensions badge on mac browsers

---

solr/Dockerfile
solr/collections/managed-schema
solr/collections/solrconfig.xml
solr/concepts/managed-schema
solr/concepts/solrconfig.xml
solr/documents/managed-schema
solr/documents/solrconfig.xml
solr/organizations/managed-schema
solr/organizations/solrconfig.xml
solr/persons/managed-schema
solr/persons/solrconfig.xml
solr/processes/managed-schema
solr/processes/solrconfig.xml
solr/relationships/managed-schema
solr/relationships/solrconfig.xml
src/main/java/edu/tamu/scholars/middleware/discovery/model/Document.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/Person.java

Solr config support version 7 and 8, keywords as whole strings

---

solr/Dockerfile
solr/collections/managed-schema
solr/collections/solrconfig.xml
solr/concepts/managed-schema
solr/concepts/solrconfig.xml
solr/documents/managed-schema
solr/documents/solrconfig.xml
solr/organizations/managed-schema
solr/organizations/solrconfig.xml
solr/persons/managed-schema
solr/persons/solrconfig.xml
solr/processes/managed-schema
solr/processes/solrconfig.xml
solr/relationships/managed-schema
solr/relationships/solrconfig.xml
src/main/java/edu/tamu/scholars/middleware/discovery/model/Document.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/Person.java
src/main/resources/templates/sparql/organization/people.sparql
src/main/resources/templates/sparql/organization/peopleTitle.sparql
src/main/resources/templates/sparql/organization/peopleType.sparql

Organization affiliated people

---

Dockerfile
README.md
pom.xml
src/main/java/edu/tamu/scholars/middleware/discovery/model/Organization.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/Relationship.java
src/main/java/edu/tamu/scholars/middleware/discovery/response/DiscoveryFacetPage.java
src/main/java/edu/tamu/scholars/middleware/graphql/model/relationship/Contributor.java
src/main/resources/defaults/discoveryViews.yml
src/main/resources/defaults/discoveryViews/publications/Book.html
src/main/resources/defaults/discoveryViews/publications/Chapter.html
src/main/resources/defaults/discoveryViews/publications/default.html
src/main/resources/defaults/displayViews.yml
src/main/resources/defaults/displayViews/documents/identity/digitalObjectIdentifier.html
src/main/resources/defaults/displayViews/documents/identity/pubMedCentralId.html
src/main/resources/defaults/displayViews/documents/overview/etdChair.html
src/main/resources/defaults/displayViews/persons/asideTemplate.html
src/main/resources/defaults/displayViews/persons/overview/keywords.html
src/main/resources/defaults/displayViews/persons/overview/keywords/default.html
src/main/resources/defaults/displayViews/relationships/affiliation/contributor.html
src/main/resources/templates/sparql/relationship/contributorRole.sparql
src/test/resources/application.yml

Docker deployment

---

src/main/java/edu/tamu/scholars/middleware/graphql/service/CollectionService.java
src/main/java/edu/tamu/scholars/middleware/graphql/service/ConceptService.java
src/main/java/edu/tamu/scholars/middleware/graphql/service/DocumentService.java
src/main/java/edu/tamu/scholars/middleware/graphql/service/OrganizationService.java
src/main/java/edu/tamu/scholars/middleware/graphql/service/ProcessService.java
src/main/java/edu/tamu/scholars/middleware/graphql/service/RelationshipService.java

This follows the same pattern as the previous simplification - except for the other types.

#177: update remaining graphql services to be simplified interface

---

src/main/java/edu/tamu/scholars/middleware/graphql/service/AbstractNestedDocumentService.java

This should make facets work again (code per William).  I couldn't seem to get change to go in from original pull request from fork (couldn't push to master without reviewer).  So made this new pull request.

Tamu lib graphql facet fix

---

src/main/java/edu/tamu/scholars/middleware/config/model/HarvesterConfig.java
src/main/java/edu/tamu/scholars/middleware/discovery/service/jena/LocalTriplestoreHarvester.java
src/main/java/edu/tamu/scholars/middleware/discovery/service/jena/TriplestoreHarvester.java
src/main/java/edu/tamu/scholars/middleware/service/SDBTriplestore.java
src/main/java/edu/tamu/scholars/middleware/service/SparqlHttpTriplestore.java
src/main/java/edu/tamu/scholars/middleware/service/TDBTriplestore.java
src/main/java/edu/tamu/scholars/middleware/service/Triplestore.java
src/main/resources/application.yml
src/test/java/edu/tamu/scholars/middleware/MiddlewareApplicationTest.java
src/test/java/edu/tamu/scholars/middleware/config/model/HarvesterConfigTest.java
src/test/java/edu/tamu/scholars/middleware/discovery/service/jena/TriplestoreHarvesterTest.java
src/test/java/edu/tamu/scholars/middleware/service/TestTriplestore.java
src/test/resources/application.yml

Proof-of-concept resolution to: https://github.com/vivo-community/scholars-discovery/issues/190

Add SPARQL over HTTP implementation of Triplestore

---

src/main/java/edu/tamu/scholars/middleware/discovery/model/Concept.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/Document.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/Organization.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/Person.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/Process.java
src/main/java/edu/tamu/scholars/middleware/discovery/model/Relationship.java

Resolves #194 
Indexing of TAMU TDB triplestore went from ~45 minutes to ~36 minutes. Running on an 8 core machine.

reduce copy fields to improve performance of index and search

---

.travis.yml
README.md
pom.xml
src/main/java/edu/tamu/scholars/middleware/auth/handler/CustomAuthenticationSuccessHandler.java
src/main/java/edu/tamu/scholars/middleware/config/WebSecurityConfig.java
src/main/java/edu/tamu/scholars/middleware/discovery/assembler/FacetPagedResourcesAssembler.java
src/main/java/edu/tamu/scholars/middleware/discovery/assembler/IndividualResourceAssembler.java
src/main/java/edu/tamu/scholars/middleware/discovery/controller/IndividualController.java
src/main/java/edu/tamu/scholars/middleware/discovery/processor/SorDocumentResourcesSearchProcessor.java
src/main/java/edu/tamu/scholars/middleware/discovery/resource/IndividualResource.java
src/main/java/edu/tamu/scholars/middleware/discovery/utility/DiscoveryUtility.java
src/main/java/edu/tamu/scholars/middleware/export/controller/IndividualExportController.java
src/main/resources/application.yml
src/main/resources/templates/helpers.js
src/test/java/edu/tamu/scholars/middleware/auth/controller/AuthControllerTest.java
src/test/java/edu/tamu/scholars/middleware/auth/controller/LoginControllerTest.java
src/test/java/edu/tamu/scholars/middleware/auth/controller/UserControllerTest.java
src/test/java/edu/tamu/scholars/middleware/discovery/controller/AbstractSolrDocumentControllerTest.java
src/test/java/edu/tamu/scholars/middleware/theme/controller/ThemeControllerTest.java
src/test/java/edu/tamu/scholars/middleware/view/controller/DirectoryViewControllerTest.java
src/test/java/edu/tamu/scholars/middleware/view/controller/DiscoveryViewControllerTest.java
src/test/java/edu/tamu/scholars/middleware/view/controller/DisplayViewControllerTest.java
src/test/resources/application.yml

197 upgrades

---

pom.xml
solr/config/solrconfig.xml
src/main/java/edu/tamu/scholars/middleware/discovery/model/repo/impl/IndividualRepoImpl.java
src/main/java/edu/tamu/scholars/middleware/discovery/response/DiscoveryFacetPage.java
src/main/java/edu/tamu/scholars/middleware/export/service/DocxExporter.java
src/main/java/edu/tamu/scholars/middleware/utility/DateFormatUtility.java

Also, cleaned up dependencies.

improve date handling, afford number range
